// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShineGuacamole.DataAccess.SqlServer.Models;

public partial class Connection
{
    public Guid ConnectionId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public byte[] Image { get; set; }

    public string Properties { get; set; }

    public string Tags { get; set; }

    public string UserId { get; set; }
}