// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ShineGuacamole.DataAccess.SqlServer.Models;

public partial class ShineGuacContext : DbContext
{
    public ShineGuacContext(DbContextOptions<ShineGuacContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Connection> Connections { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Connection>(entity =>
        {
            entity.Property(e => e.ConnectionId).ValueGeneratedNever();
            entity.Property(e => e.Image).HasColumnType("image");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Properties).IsRequired();
            entity.Property(e => e.Tags).HasMaxLength(100);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(80)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}